#!/usr/bin/env bash

export GIT_COMMITTER_NAME="YOUR NAME"
export GIT_COMMITTER_EMAIL="your.email@your-anonymous-provider.com"
export GIT_AUTHOR_NAME="YOUR NAME"
export GIT_AUTHOR_EMAIL="your.email@your-anonymous-provider.com"
